services:
  postgres:
    container_name: postgresF
    image: postgres
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5435:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadminF
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
      - app
    restart: unless-stopped

  customer-api:
    container_name: customer-api
    image: serikmeiirbek/customer-api:20.07.2023.05.02.59
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/amigoscode"
    ports:
      - "8088:8080"
    networks:
      - postgres
    depends_on:
      - postgres
    restart: unless-stopped


  customer-react:
    container_name: customer-react
    image: serikmeiirbek/customer-react:latest
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - customer-api
    restart: unless-stopped



networks:
  postgres:
    driver: bridge
  app:
    driver: bridge

volumes:
  postgres:
  pgadmin: